name: The Internet of Things
favicon: null
layout_spectrum: 1
typography_spectrum: 0.6828520111739635
title: The Future of Technology
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#008aa5'
    - '#003a44'
    - '#fdfefe'
    - '#4a6e0f'
    - '#b28a34'
  brandStrength: 0.8661845324095339
  lightness: 0.4208367362152785
  saturation: 0.6615487015806139
  rhythmicContrast: 0.7685205640736967
purpose: []
